# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

dist: trusty
sudo: false

env:
  - KERAS_BACKEND="tensorflow"
  - KERAS_BACKEND="theano" THEANO_FLAGS=optimizer=fast_compile
  - KERAS_BACKEND="cntk" PYTHONWARNINGS=ignore
  - KERAS_IMPLEMENTATION="tensorflow"

cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

addons:
  apt:
    packages:
    - openmpi-bin
    - python-dev 
    - libffi-dev 
    - libssl-dev

before_script:
  - pip2.7 install --upgrade --ignore-installed --user pyopenssl ndg-httpsclient pyasn1
  - pip2.7 install --upgrade --ignore-installed --user travis pip setuptools wheel virtualenv
  - pip2.7 install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - pip2.7 install --upgrade --ignore-installed --user https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3-cp27-cp27mu-linux_x86_64.whl
  - R -e 'tensorflow::install_tensorflow()'


